destination:
  server: https://kubernetes.default.svc
source:
  repoURL: http://gitea-127.0.0.1.sslip.io:30950//dag.git
  targetRevision: k3s
gitea:
  server:
    outClusterURL: http://gitea-127.0.0.1.sslip.io:30950
    inClusterURL: 
  oAuthSecret: demo-oauth--secret
  username: 
  password: @123
drone:
  server:
    version: 0.6.0
    host: http://drone-127.0.0.1.sslip.io:30980
    namespace: drone
    hostAliases:
      - ip: 10.43.224.93
        hostnames:
          - gitea-127.0.0.1.sslip.io
    admin:
      enable: true
argocd:
  imageUpdater:
    versio: 0.8.0
    logLevel: debug
    registries:
      - name: "myregistry.localhost"
        prefix: "myregistry.localhost:5001"
        api_url: "http://myregistry.localhost:5001"
        default: true
        defaultns: example
        insecure: true
artifactory:
    enabled: 